import React from 'react'
import type { DocsThemeConfig } from 'nextra-theme-docs'

const config: DocsThemeConfig = {
  logo: <span style={{ fontWeight: 700 }}>Personal Finance Docs</span>,
  
  docsRepositoryBase: 'https://github.com/',
  useNextSeoProps() {
    return { titleTemplate: '%s – Personal Finance Docs' }
  },
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="AI-powered personal finance tracker — upload bank statements, auto-categorize transactions with Claude, and visualize spending across budgets, categories, timelines, and income. Built with Next.js, Supabase, and Google OAuth." />
    </>
  ),
  footer: { text: <span>Generated by doc-generator skill</span> },
}

export default config
