import { Layout, Navbar } from 'nextra-theme-docs'
import { Head } from 'nextra/components'
import { getPageMap } from 'nextra/page-map'
import 'nextra-theme-docs/style.css'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
  title: {
    template: '%s – Personal Finance Docs',
    default: 'Personal Finance Docs',
  },
  description:
    'AI-powered personal finance tracker — upload bank statements, auto-categorize transactions with Claude, and visualize spending across budgets, categories, timelines, and income.',
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  const pageMap = await getPageMap()
  return (
    <html lang="en" suppressHydrationWarning>
      <Head />
      <body>
        <Layout
          navbar={<Navbar logo={<b>Personal Finance Docs</b>} />}
          footer={<p>Generated by doc-generator skill</p>}
          docsRepositoryBase="https://github.com/catalinnita/personal-finance"
          pageMap={pageMap}
        >
          {children}
        </Layout>
      </body>
    </html>
  )
}
